---

- name: Configure passwordless SSH access

  hosts: spot_vms

  become: true

  tasks:

    - name: Ensure .ssh directory exists

      file:

        path: /home/centos/.ssh

        state: directory

        owner: centos

        group: centos

        mode: '0700'

    - name: Copy SSH public key to authorized_keys

      copy:
        src: /home/centos/.ssh/id_rsa.pub
        dest: /home/centos/.ssh/authorized_keys
        
    - name: Ensure correct permissions for authorized_keys

      file:

        path: /home/centos/.ssh/authorized_keys

        owner: centos

        group: centos

        mode: '0600'
